;-----------------------------------------------------------------------------
;  SpinUp configuration file for CoLM
;-----------------------------------------------------------------------------

[BaseInfo]
CoLMCoreNum       = 128
ScriptPath        = /home/wumej22/drive/Omarjan/CRESMDataPrep/SpinUpScript
CoLMPath          = /stu01/wumej22/CRESM/CRESM_wn_0521/MODEL/CRESM_master_250305/CoLM/CoLM202X             
CoLMRawDataPath   = /shr03/CoLMrawdata
CoLMRunDataPath   = /shr03/CoLMruntime
CoLMForcDataPath  = /shr03/CoLM_Forcing
CleanTempFiles    = True



[SpinUp]
GoMakeIni         = True
GoFirstPeriod     = True
GoSecondPeriod    = True
GoThirdPeriod     = True


[Yangtze_6km_2018]
CoLMCasePath      = /tera07/zhangsl/wumej22/Omarjan/CRESMDataPrep/Cases/Yangtze_6km_2018/Yangtze_6km_2018
MeshFilePath      = /tera07/zhangsl/wumej22/Omarjan/CRESMDataPrep/Cases/Yangtze_6km_2018/Yangtze_6km_2018/mesh_cwrf_Yangtze_6km_2018.nc
SpinUpStartTime   = 1991-01-01_00:00:00
SpinUpEndTime     = 2000-01-01_00:00:00
TimeStep          = 3600
ForcingDataName   = ERA5LAND
WriteRestartFreq  = YEARLY, MONTHLY, DAILY
WriteHistoryFreq  = YEARLY, YEARLY, YEARLY



